---
# tasks file for ansible-role-jitsi-meet-web

- name: install base packages
  apt:
    pkg:
    - ufw
    - bmon
    - htop
    - vim
    - ssl-cert
    - nginx

- name: configure firewall rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { rule: 'allow', port: '22', proto: 'tcp' }
    - { rule: 'allow', port: '80', proto: 'tcp' }
    - { rule: 'allow', port: '443', proto: 'tcp' }

- name: set logging
  ufw:
    logging: 'off'

- name: set ufw policy
  ufw:
    state: enabled
    policy: deny

- name: add gpg key for jitsi repo
  apt_key:
    url: https://download.jitsi.org/jitsi-key.gpg.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/jitsi.gpg

- name: add jitsi-meet stable apt repo
  apt_repository:
    repo: deb https://download.jitsi.org stable/
    state: present
    filename: jitsi

- name: install jitsi-meet-web
  apt:
    name: jitsi-meet-web
    state: latest

- name: jitsi meet config directory
  file:
    path: /etc/jitsi/meet
    state: directory

- name: deploy jitsi-meet-web config template
  template:
    src: config.js.j2
    dest: /etc/jitsi/meet/{{jitsi_domain}}-config.js

- name: deploy jitsi-meet-web config template
  template:
    src: interface_config.js.j2
    dest: /etc/jitsi/meet/{{jitsi_domain}}-interface_config.js

- import_role:
    name: nginx
  vars:
    nginx_vhosts: []

- name: flush handlers
  meta: flush_handlers

- import_role:
    name: certificate
  vars:
    certificate_name: "{{ jitsi_meet_web_hostname }}"
    certificate_directory: /etc/ssl
    certificate_key_usage:
      - digitalSignature
      - keyEncipherment
    certificate_extended_key_usage:
      - serverAuth
    certificate_common_name: "{{ jitsi_meet_web_hostname }}"

- import_role:
    name: nginx
  vars:
    nginx_vhosts: "{{ jitsi_meet_web_nginx_vhosts }}"
